### ISSUE TITLE
FAQ should indicate the that the Jython version number moves in lockstep with the Python version it purports to implement

### ISSUE THREAD

**Issue by paul-hammant** [jython/jython.github.io#1]
For example Jython 2.7.1 is tracking Python 2.7.1

Or maybe that's not the case, but it has not been made explicit (the 2.7.1 blog entry, the front page of the Jython site, the FAQ).

**Comment by jeff5** [comment]
No that's not the case. As with CPython, <major>.<minor> denotes the version of the language, and the .<micro> is just a one-up release.

With 2.7, this practice is stretched to breaking point because of the determination that there shall never be a 2.8, and the library (if not the language) moved quite a long way during 2.7. We think we are a patchy equivalent to CPython 2.7.10-ish, but it's not simple to compare.
